FixedCapacityStackOfStringsTest: FixedCapacityStackOfStrings.o FixedCapacityStackOfStringsTest.o 
	g++ -g -Wall FixedCapacityStackOfStringsTest.o FixedCapacityStackOfStrings.o -o FixedCapacityStackOfStringsTest

FixedCapacityStackOfStringsTest.o: FixedCapacityStackOfStringsTest.cpp
	g++ -g -Wall -c FixedCapacityStackOfStringsTest.cpp

FixedCapacityStackOfStrings.o : FixedCapacityStackOfStrings.cpp FixedCapacityStackOfStrings.h
	g++ -g -Wall -c FixedCapacityStackOfStrings.cpp
